### ISSUE TITLE
Trading Post not working?

### ISSUE THREAD

**Issue by toritazer** [Calemi/CalemiEconomy-1.18.1#5]
Hi i have this mod on my server for 1.18.2 forge 40.2.2 and when placing something in the trading post we cant sent a price there are no - or + buttons??

**Comment by Calemi** [comment]
You have to scroll on the number to change it. Hope this helps!

**Comment by toritazer** [comment]
OMG THANK YOU!!!!!!!

**Comment by Calemi** [comment]
No problem!
